# Render.com deployment configuration for Aeonark Labs
services:
  - type: web
    name: aeonark-labs
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    branch: main
    
    # Environment variables (set these in Render dashboard)
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
      - key: GMAIL_USER
        sync: false  # Set this in Render dashboard
      - key: GMAIL_PASSWORD
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: SUPABASE_URL
        sync: false  # Set this in Render dashboard
      - key: SUPABASE_ANON_KEY
        sync: false  # Set this in Render dashboard
      - key: SUPABASE_SERVICE_KEY
        sync: false  # Set this in Render dashboard
    
    # Health check
    healthCheckPath: /api/health
    
    # Auto-deploy
    autoDeploy: true
    
    # Build command (handled by Dockerfile)
    # buildCommand: ""
    
    # Start command (handled by Dockerfile)
    # startCommand: ""